import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";

export default function Home({ cities, exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>Airbnb App | React & Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airbnb.ico" />
      </Head>

      <Header cities={cities} />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2
            className="text-5xl font-semibold pb-5 bg-gradient-to-r 
          from-red-400 to-[#7D3155] text-transparent bg-clip-text"
          >
            Explore Nearby
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData.record?.map(({ img, distance, location }) => (
              <SmallCard
                key={img}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>

        <section className="mt-10">
          <h2
            className="text-5xl font-semibold py-8
          bg-gradient-to-r from-red-400 via-[#7D3155] to-[#7D3155]
          text-transparent bg-clip-text max-w-[500px]"
          >
            You don&apos;t need to go far to find what matters
          </h2>

          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData.record?.map(({ img, title, subtitle }) => (
              <MediumCard
                key={img}
                img={img}
                title={title}
                subtitle={subtitle}
              />
            ))}
          </div>
        </section>

        <LargeCard
          img="https://www.androidauthority.com/wp-content/uploads/2021/03/airbnb-example-home-scaled-e1644903817613.jpg"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const baseURL = "https://api.jsonbin.io/v3/b/";

  const exploreData = await fetch(`${baseURL}64ca4565b89b1e2299c9fc87`).then(
    (res) => res.json()
  );

  const cardsData = await fetch(`${baseURL}64ca53efb89b1e2299ca04d9`).then(
    (res) => res.json()
  );

  const cities = await fetch("https://api.npoint.io/eb5569e875931c04fc89").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      cardsData,
      cities,
    },
  };
}
